# Generated by Django 2.2.5 on 2019-09-28 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegisteredDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('poject_domain', models.CharField(max_length=255)),
                ('project_name', models.CharField(max_length=255)),
                ('phone_no', models.IntegerField()),
            ],
        ),
    ]
